name: Deploy to Development v3

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build:${{ inputs.environment }}
