name: Deploy to Development v4

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Echo
        run: echo "The operating system on the runner is $env:RUNNER_OS. $env:API_URL"

      - name: Build project
        run: yarn build:${{ inputs.environment || 'dev' }}
