name: Dev workflow

on:
  workflow_dispatch:

env:
  API_URL: 'test'

jobs:
  workflow_v1:
    uses: M4rk98/feed.react/.github/workflows/code-quality.yml@master
    with:
      environment: 'dev'
  workflow_step2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Echo'
        run: echo "The operating system on the runner is $RUNNER_OS. $API_URL" + ${{ runner.os }}
